defaults:
  - _self_
  - user_settings: user_settings
  - hydra: base
  - llm: local

project_path: ${user_settings.project_path}
result_dir: ${user_settings.result_dir}
hydra_root: ${user_settings.hydra_root}
hydra_dir: ${user_settings.hydra_dir}

# Bot configuration
telegram_bot_token: ${user_settings.telegram_bot_token}
notes_directory: ${user_settings.notes_directory}

# LLM prompts
question_generation_prompt: |
  ### Инструкция ###
  Ты являешься помощником в образовательном процессе. Ниже дан абзац текста из обучающей программы. Задай вопрос по этому абзацу. В ответе должен быть только запросов без каких-либо вводных и заключительных конструкций.

  ### Абзац ###
  {paragraph}

answer_scoring_prompt: |
  ### Инструкция ###
  Ты являешься помощником в образовательном процессе. Ниже даны абзац текста из обучающей программы и вопрос по этому абзацу. Затем дан ответ студента на этот вопрос. Оцени, насколько этот ответ является верным с точки зрения информации, предоставленной в абзаце. Твой ответ должен быть представлен в json формате {{"score": ..., "explanation": ...}}, где score является оценкой от 0 до 3 и explanation является кратким объяснением, почему именно такая оценка была поставлена со ссылкой на конкретную информацию в абзаце. Используй следующую шкалу оценок:
  - 0: полностью некорректный или нерелевантный ответ
  - 1: частично корректный ответ, но некоторые ключевые моменты пропущены
  - 2: почти корректный ответ, в котором пропущены некоторые детали
  - 3: полностью корректный ответ

  ### Абзац ###
  {paragraph}

  ### Вопрос ###
  {question}

  ### Ответ студента ###
  {user_answer}
